experiment: loong
system: direct_no_tool_use
system_config:
  models:
    tool_use:
      model: gpt-4.1
      max_completion_tokens: 8192
      temperature: 0.0
    answer:
      model: gpt-4.1
      max_completion_tokens: 8192
      temperature: 0.0
experiment_config:
  benchmark_path: /data1/hypothesis_dataset/loong/loong_processed.jsonl
  gpt_results_path: /data1/hypothesis_dataset/loong/results/gpt-4_oracle_reverse.jsonl
  files_dir: /data1/hypothesis_dataset/loong/doc/
  soft_evaluator_model: gpt-4.1
  hard_evaluator_model: gpt-4.1
  # specific_ids_csv: notebooks/50_sample_ids_finance.csv
  num_questions: null
  random_state: 42
  docprocesssing: False
  filter_by_type: "financial"
output_file: loong_direct_without_tool_use_gpt-4.1_finance.json